apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-service-dev
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-service-dev
  template:
    metadata:
      labels:
        app: scheduler-service-dev
    spec:
      containers:
      - name: scheduler-service-dev
        image: host.minikube.internal:5000/scheduler_service_dev:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: TZ
          value: "Asia/Singapore"  # GMT+8 timezone
        envFrom:
        - configMapRef:
            name: scheduler-service-dev-env
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: default
spec:
  selector:
    app: scheduler-service-dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
