apiVersion: v1
kind: Service
metadata:
  name: pear-schedule-service
  labels:
    app: pear-schedule
    project: pear
spec:
  selector:
    app: pear-schedule
    project: pear
  ports:
    - name: pear-scheduler-http
      protocol: TCP
      port: 8080
      targetPort: 8080
